### ISSUE TITLE
Update delaunay

### ISSUE THREAD

**Issue by acgetchell** [oovm/shape-rs#1]
Hello,

I’d like to start maintaining and updating this crate. I’m doing research that needs performant Delaunay triangulations without dependencies on CGAL or the other libraries I’ve been using in C++ for the past few years.

Thanks for your consideration!

**Comment by oovm** [comment]
I'm happy to change the implementation, but the bigger difficulty for me is that this is a generic library. With generics, you can't specialize f32 and f64, and throughput is a problem.

**Comment by oovm** [comment]
Metadata can be attached to PointSet/TriangleSet, etc., and the elements in the set can be efficiently associated through index.

But I still think that metadata should be placed externally. In my opinion, there are two types of metadata

- One is dense, such as location information, each element needs.
- One is sparse, such as node coloring, node connection, some elements are required, and other elements may be default values.

It is not appropriate to put these attributes in Point, which will cause the structure to expand and reduce cache efficiency and throughput.

**Comment by acgetchell** [comment]
Okay ... are you adding d-dimensional triangulations? As far as I can tell, there hasn't been activity for 6 years, and you were looking for new maintainers. Are you taking pull requests for new code? It looks like this has been moved to some type of super repo of related projects? Which repo would I submit them to?

Thanks.

**Comment by oovm** [comment]
Just submit it to this repo. I'm actually updating the dependencies and edition.

I won't update more features just because I won't be engaged in graphics after graduation.

Any new feature submissions are welcome

---

It is necessary to define high-dimensional simplexes first.

This library did not consider k-dimensional situations when designing.

At that time, `const N: usize` was not stable either.

```rust
struct Simplex<T, const N: usize> {
    points: [Point<T>; N]
}
```

But this makes it impossible to parse the data from the text. It seems better to change to Vec.

**Comment by oovm** [comment]
Or we should use nightly feature more radically. 

As far as I know, the [specialization](https://rust-lang.github.io/rfcs/1210-impl-specialization.html) proposal can provide specialized implementation.

Although this is a generic library, optimized function can be implemented separately for f32 and f64.

**Comment by oovm** [comment]
I have transferred the ownership of the [delaunay](https://crates.io/crates/delaunay) crate. 

If you need to share some definitions, such as high-dimensional Simplex or Triangulation traits, you are welcome to open new issue and submit a PR.
